### ISSUE TITLE
Error building libRocket on Ubuntu 15.10

### ISSUE THREAD

**Issue by sweatybridge** [davedissian/dawnengine#4]
Not sure if you have encountered this problem before?

```
/usr/bin/ld: /home/qh812/project/dawnengine/dependencies/linux-build/ogredeps/ogredeps/lib/libfreetype.a(ftbase.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/qh812/project/dawnengine/dependencies/linux-build/ogredeps/ogredeps/lib/libfreetype.a: error adding symbols: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/RocketCore.dir/build.make:3336: recipe for target 'libRocketCore.so.1.3.0.0' failed
make[2]: *** [libRocketCore.so.1.3.0.0] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/RocketCore.dir/all' failed
make[1]: *** [CMakeFiles/RocketCore.dir/all] Error 2
```

**Comment by davedissian** [comment]
Oh woops! That requires a patch in the ogredeps CMakeLists.txt to support the Clang compiler correct (which I've done but forgot to reupload the dependencies archive). A workaround for the time being would be to remove the export CC and export CXX lines in the build-unix.sh script so it builds using GCC rather than Clang.

Bare in mind the engine is currently in a very unusable state - working on building a working sandbox mode after exams.

**Comment by davedissian** [comment]
Closing this, as I've now integrated libRocket directly into the build.
